### Embedding layer
An embedding layer is a word embedding technique used in natural language processing. It is one of the available layers in Keras i.e., Keras provides an Embedding layer that can be used for neural networks on text data. The embedding layer is defined as the first hidden layer of the network. 

This layer takes three arguments:

1. input_dim: the size of the vocabulary in text data

2. output_dim: the size of the output or vector space that the words will be embedded.

3. input_length: length of the input sequences

In [1]:
import tensorflow as tf
tf.__version__

reviews=['awesome movie',
         'not good',
         'I loved this movie',
         'Good direction',
         'awful',
         'rocks',
         'Never coming back',
         'bad story'
]

### Vocabulary size
voc_size=5000

# One hot representation
from tensorflow.keras.preprocessing.text import one_hot
onehot=[one_hot(words,voc_size) for words in reviews] 
print(onehot)

# Embeding Layer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

max_length=4
embedded_docs=pad_sequences(onehot,padding='post',maxlen=max_length)
print(embedded_docs)

model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=10,input_length = max_length))
model.compile(optimizer='adam', loss='binary_crossentropy')

model.summary()
model.predict(embedded_docs)

print(model.predict(embedded_docs[0:1]))

[[4562, 2093], [4431, 3262], [1903, 232, 732, 2093], [3262, 4325], [4631], [1236], [1455, 4750, 2022], [3829, 2323]]
[[4562 2093    0    0]
 [4431 3262    0    0]
 [1903  232  732 2093]
 [3262 4325    0    0]
 [4631    0    0    0]
 [1236    0    0    0]
 [1455 4750 2022    0]
 [3829 2323    0    0]]


C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
[[[-0.0483201   0.00497489  0.03174654 -0.02011378  0.00054219
   -0.04433118 -0.01446939 -0.02613629  0.02391114  0.00815699]
  [ 0.00912185 -0.00460912  0.04584043  0.00646381  0.02914666
    0.02007381  0.01732269 -0.02191433  0.00620554 -0.03475727]
  [ 0.04468359  0.04495737  0.04040153  0.02933589 -0.04821653
    0.03711981  0.01769166 -0.02213345  0.04760144 -0.01024184]
  [ 0.04468359  0.04495737  0.04040153  0.02933589 -0.04821653
    0.03711981  0.01769166 -0.02213345  0.04760144 -0.01024184]]]


### Word2Vec in NLP | Natural Language Processing
Word2Vec is a method for converting words to numbers or vector representations. This technique was published in 2013. This algorithm includes skip-gram and CBOW models (Continuous Bag of Words model).

In [2]:
Paragraph= """Frequently Asked Questions
The Basics
What is Colaboratory?
A product of Google Research is Colaboratory, or "Colab" for short. Colab excels in three areas: machine learning, teaching, and data analysis. Through the browser, anyone may write and run arbitrary Python code. In terms of technology, Colab is a hosted Jupyter notebook service that provides free access to computer resources, including GPUs, and doesn't require any setup to use.

Is it really free to use?
Yes. Colab is free to use.

Seems too good to be true. What are the limitations?
Colab's resources are neither endless or guaranteed, and the consumption caps occasionally change. In order for Colab to offer materials for free, this is required. For more details, see Resource Limits

Colab Pro can be of interest to users who want more dependable access to greater resources.

What is the difference between Jupyter and Colab?
Colab is built on the open-source project Jupyter. You can use and share Jupyter Notebooks with others using Colab without having to download, install, or run anything.

Using Colab
What happened to my notebooks, and can I share them?
Colab notebooks are saved in Google Drive and can also be imported from GitHub. Similar to how Google Docs or Sheets may be shared, Colab notebooks can as well. Simply utilize the Google Drive file sharing instructions or click the Share icon in the upper right corner of any Colab notebook.

What will be shared if I share my notebook?
The complete contents of your notebook (text, code, output, and comments) are shared when you share a notebook. By selecting Edit > Notebook settings > Omit code cell output when saving this notebook, you can prevent saving or sharing code cell output. The virtual machine you're using, as well as any custom files and libraries you've installed, will not be shared. As a result, it's a good idea to include cells that install and load any custom libraries or files required by your notebook.

Is it possible to import an existing Jupyter/IPython notebook into Colab?
Yes. From the File menu, select "Upload notebook".

How can I search Colab notebooks?
You can search Colab notebooks using Google Drive. All notebooks in Drive can be viewed by clicking on the Colab logo at the top left of the notebook view. You may also use File > Open notebook to look for notebooks you've recently opened.

Where is my code executed? When I close the browser window, what happens to my execution state?
The code is run in a virtual computer dedicated to your account. Virtual machines are removed after a period of inactivity, and the Colab service enforces a maximum lifetime.

How can I get my data out?
You can download any Colab notebook you've made from Google Drive using these methods, or from the File menu in Colab. The open source Jupyter notebook format (.ipynb) is used to store all Colab notebooks.

How can I reset the virtual machine(s) on which my code runs, and why is this occasionally unavailable?
Select Runtime > Factory reset runtime to restore the original state of all managed virtual machines allocated to you. This can be useful when a virtual machine has become unhealthy, for example, due to an inadvertent overwrite of system files or the installation of incompatible applications. To avoid excessive resource consumption, Colab limits how frequently this can be done. Please try again later if an attempt fails.

Why does drive.mount() occasionally fail with a "timed out" error, and why do I/O operations in drive.mount()-mounted folders occasionally fail?
When the number of files or subfolders in a folder becomes too enormous, Google Drive activities may time out. If the top-level "My Drive" folder contains thousands of objects, mounting the drive will most certainly fail. Failed attempts cache partial state locally before stalling out, so repeated attempts may finally succeed. If you run into this issue, try transferring files and folders directly from "My Drive" into subfolders. When reading from other directories after a successful drive.mount(), a similar situation can arise. Accessing items in any folder with multiple items can result in issues such as OSError: [Errno 5] Input/output error.  Again, you can resolve this issue by relocating directly enclosed items into subfolders.
It's worth noting that "deleting" files or subfolders by transferring them to the Trash may not be adequate; if that doesn't appear to help, Empty your Trash.

Why do Drive operations occasionally fail owing to quota constraints?
Google Drive imposes several restrictions, such as per-user and per-file operation counts and bandwidth constraints. Exceeding these restrictions will result in the same Input/Output error as described above, as well as a message in the Colab UI. Accessing a popular shared file, or accessing too many separate files too soon, is a common reason. Workarounds include:

To prevent other users from exceeding its limits, copy the file using drive.google.com and don't distribute it around.
Choose to copy data from Drive to the Colab VM in an archive format (such as.zip or.tar.gz files) and unarchive the data locally on the VM rather than in the mounted Drive directory to avoid doing several short I/O reads.
Wait till the quotas reset the following day.
Why do storage quota-related drive activities occasionally fail?
The amount of data that each user can save in Google Drive is restricted. If you need to free up space and Google Drive operations are failing with input/output errors or you receive a message that your storage quota has been exceeded, remove some files using drive.google.com and empty your trash. The reclaimed space might not be accessible in Colab right away.

Visit Google Drive to acquire additional Drive space. Please take note that purchasing more Drive space will not result in more disk space becoming accessible for Colab VMs. Subscribing to Colab Pro will.

Resource Limits
Why aren’t resources guaranteed in Colab?
Colab must continue to be adaptable enough to change usage restrictions and hardware availability as needed in order to provide computing resources without charge. The resources that Colab has available change over time to meet changing demand, as well as to support overall growth and other variables.

The resource restrictions prevent some users from doing everything they wish to do in Colab. Many users have expressed a desire for faster GPUs, longer-lasting notebooks, more RAM, greater usage caps, and less erratic usage patterns. The first step we are taking to assist consumers who want more out of Colab is introducing Colab Pro. Our long-term objective is to maintain a free version of Colab while expanding sustainably to serve our users' requirements. Please sample Colab Pro and let us know what you think if you're interested in doing more with Colab than the resource restrictions of the free edition of Colab permit.

What are the usage limits of Colab?
Colab is able to offer free resources in part because it uses dynamic usage caps that occasionally change and does not guarantee or supply unlimited resources. This implies that overall utilization caps, idle timeout durations, maximum VM lifetimes, available GPU kinds, and other parameters change over time. These restrictions are not made public by Colab in part because they can—and occasionally do—change quickly.

Sometimes, users who use Colab interactively rather than for lengthy computations or users who have recently utilized fewer resources in Colab have priority access to GPUs and TPUs. As a result, users who use Colab for lengthy calculations or users who have recently accessed more resources in Colab are more likely to hit utilization caps and have temporary access restrictions placed on GPU and TPU usage. Colab's user interface may be used in conjunction with a local runtime running on the user's own hardware if they have high computing requirements. Colab Pro may be of interest to users who want larger and more reliable use limitations.

What types of GPUs are available in Colab?
As time goes by, several GPU models become available in Colab. For Colab to be able to offer free access to these resources, this is necessary. Nvidia K80s, T4s, P4s, and P100s are frequently among the GPUs that are offered in Colab. What kind of GPU you can connect to at any given time in Colab cannot be selected. Colab Pro might be of interest to those who want more dependable access to Colab's fastest GPUs.

It should be noted that using Colab to mine cryptocurrencies is completely prohibited and may result in your account being completely blocked from using Colab.

How long can notebooks run in Colab?
Virtual machines that can last up to 12 hours at their maximum lifetime are connected to the notebooks that execute them. When kept idle for too long, notebooks will also disconnect from virtual machines. The behavior of the maximum VM lifetime and the idle timeout may change over time or depending on your usage. In order for Colab to provide free computational resources, this is necessary. Colab Pro might be of interest to users that want more stable idle timeout behaviors over time and longer VM lifetimes.

How much memory is available in Colab?
Colab virtual machines' memory allocation changes with time (albeit it remains constant for the duration of the VM). (Over time, RAM can be adjusted, allowing us to keep Colab free.) When Colab determines that you are going to need more memory, you might occasionally be automatically given a VM with more of it. Users that want Colab to run more reliably and with more memory may be interested in Colab Pro.

How can Colab best serve my needs?
In order to avoid a small number of users monopolizing scarce resources, Colab prioritizes resources for users who have recently consumed fewer resources. Consider closing your Colab tabs when you are finished with your work in order to get the most out of Colab. You should also avoid choosing a GPU if it is not necessary for your job. You will be less likely to encounter use caps in Colab as a result of this. Colab Pro may be of interest to users who want to use more resources than are permitted by the free edition of Colab.

My GPU is not being used, according to a message I noticed. What ought I to do?
Accelerated computing environments like GPU and TPU are optional at Colab. The GPU or TPU is not necessarily being used just because code is being run in a GPU or TPU runtime. If you are not using the GPU, we advise switching to a standard runtime to prevent exceeding your GPU usage restrictions. Select Hardware Accelerator from the Runtime > Change Runtime Type menu and set it to None.

See the Tensorflow With GPU and TPUs In Colab example notebooks for demonstrations of how to use GPU and TPU runtimes in Colab.

Additional Questions
What browsers are supported?
The most recent versions of Chrome, Firefox, and Safari were used for the most extensive testing of Colab's compatibility with most popular browsers.

How is this related to colaboratory.jupyter.org?
We collaborated with the Jupyter development team in 2014 to produce a prototype of the tool. Colab has now developed further under the direction of internal usage.

What about other programming languages?
Python and its ecosystem of complementary tools are the main areas of concentration for Colab. We are aware that customers would like support for more Jupyter kernels, such as R or Scala. Although we have no ETA at this time, we would like to support these.

I found a bug or have a question, who do I contact?
Open any Colab notebook. Then choose "Send feedback..." from the Help menu.

Why prompt to enable third-party cookies?
To display rich outputs securely, Colab leverages HTML iframes and service workers hosted on different origins. To use the service workers within iframes, browsers need to have third-party cookies enabled. If you choose not to enable third-party cookies for all websites, you can allow the hostname googleusercontent.com in your browser's settings.

How do I change the editor font?
The editor in Colab employs a simple monospace font. In the majority of contemporary browsers, you can specify which font family is used for monospace. Here's a few common ones:

To configure the "Monospace" font in Firefox, follow the instructions in the Firefox support manuals.
In Chrome, navigate to "chrome://settings/fonts" and modify the section labeled "Fixed-width font".
Does Colab support Python 2?
According to the Python development team, Python 2 will no longer get security updates or bug fixes after January 1st, 2020. Colab is gradually discontinuing support for Python 2 notebooks and has stopped updating the Python 2 runtimes. We advise switching crucial notebooks to Python 3.

To change your Python 2 notebook's runtime to Python 3, choose Runtime > Change Runtime Type and select Python 3. Changing the runtime from Python 3 to Python 2 is not supported. See Porting Python 2 Code to Python 3 for instructions on making the switch from Python 2 to Python 3.

Where can I learn more about Colab Pro?
There is an FAQ for Colab Pro on the Colab Pro sign-up page.
"""

In [3]:
# Preprocessing the data and preparing the dataset
import nltk
import re
from gensim.models import Word2Vec
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
sentences = nltk.sent_tokenize(Paragraph)
final_text = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [word for word in review if word not in set(stopwords.words('english'))]
    final_text.append(review)
print(final_text)
print(len(final_text))

[['frequently', 'asked', 'questions', 'basics', 'colaboratory'], ['product', 'google', 'research', 'colaboratory', 'colab', 'short'], ['colab', 'excels', 'three', 'areas', 'machine', 'learning', 'teaching', 'data', 'analysis'], ['browser', 'anyone', 'may', 'write', 'run', 'arbitrary', 'python', 'code'], ['terms', 'technology', 'colab', 'hosted', 'jupyter', 'notebook', 'service', 'provides', 'free', 'access', 'computer', 'resources', 'including', 'gpus', 'require', 'setup', 'use'], ['really', 'free', 'use'], ['yes'], ['colab', 'free', 'use'], ['seems', 'good', 'true'], ['limitations'], ['colab', 'resources', 'neither', 'endless', 'guaranteed', 'consumption', 'caps', 'occasionally', 'change'], ['order', 'colab', 'offer', 'materials', 'free', 'required'], ['details', 'see', 'resource', 'limits', 'colab', 'pro', 'interest', 'users', 'want', 'dependable', 'access', 'greater', 'resources'], ['difference', 'jupyter', 'colab'], ['colab', 'built', 'open', 'source', 'project', 'jupyter'], ['use'

In [4]:
# Training the Word2Vec model
model = Word2Vec(final_text)
print(model)

Word2Vec<vocab=48, vector_size=100, alpha=0.025>


In [5]:
# finding vocabulary
#vocab = model.wv.vocab
#print(vocab.keys())

vocab = model.wv.key_to_index
print(vocab)

{'colab': 0, 'drive': 1, 'python': 2, 'notebooks': 3, 'resources': 4, 'notebook': 5, 'users': 6, 'gpu': 7, 'google': 8, 'pro': 9, 'use': 10, 'free': 11, 'may': 12, 'runtime': 13, 'change': 14, 'time': 15, 'using': 16, 'usage': 17, 'files': 18, 'virtual': 19, 'occasionally': 20, 'jupyter': 21, 'code': 22, 'restrictions': 23, 'vm': 24, 'result': 25, 'file': 26, 'want': 27, 'run': 28, 'support': 29, 'used': 30, 'output': 31, 'caps': 32, 'gpus': 33, 'access': 34, 'font': 35, 'tpu': 36, 'available': 37, 'space': 38, 'fail': 39, 'machines': 40, 'shared': 41, 'share': 42, 'interest': 43, 'limits': 44, 'resource': 45, 'order': 46, 'data': 47}


In [6]:
# Finding Word Vectors
vector = model.wv['colab']
print(vector)

[-5.1121728e-04  2.7032322e-04  5.0249058e-03  9.0662185e-03
 -9.3368990e-03 -7.3825442e-03  6.6656927e-03  9.3167042e-03
 -5.0461995e-03 -4.0317131e-03  7.5920797e-03 -1.6662350e-03
 -4.5042560e-03  6.8036485e-03 -4.9896692e-03 -1.8348630e-03
  3.2211933e-03  1.0067798e-03 -8.2240198e-03 -9.7985510e-03
  7.5437175e-03  5.1301154e-03  7.1121673e-03  7.6209917e-04
  6.3411463e-03 -3.4881856e-03 -1.0657348e-03  5.8529642e-03
 -7.5945989e-03 -3.9699976e-03 -7.2928765e-03 -8.8376610e-04
  9.7867511e-03 -7.5840065e-03 -2.4360593e-03 -1.7169322e-03
  8.2259886e-03 -6.0054222e-03 -2.5037053e-04 -4.7638016e-03
 -9.5656868e-03  4.9526081e-03 -8.7351818e-03 -4.5575439e-03
  7.3568728e-05 -3.6780856e-04 -7.8394488e-03  9.4848815e-03
  5.0859610e-03  9.3362993e-03 -8.0573214e-03  4.4907359e-03
 -4.3359525e-03  8.1113342e-04  8.4505258e-03 -4.5133899e-03
  4.6609128e-03 -6.8828440e-03 -3.6889573e-03  9.3675507e-03
 -1.6563053e-03  1.1473657e-04 -3.8328308e-03 -7.5432640e-03
 -1.7142914e-03  2.71531

In [7]:
# Most similar words
similar = model.wv.most_similar('notebooks')
similar

[('change', 0.18186838924884796),
 ('tpu', 0.16657355427742004),
 ('resource', 0.1530623435974121),
 ('notebook', 0.1360807716846466),
 ('share', 0.07930631190538406),
 ('google', 0.07655245065689087),
 ('access', 0.07257746160030365),
 ('drive', 0.07195565104484558),
 ('users', 0.053904708474874496),
 ('vm', 0.05049266293644905)]

In [8]:
# finding similarity score between two words in vocab
model.wv.similarity(w1="jupyter",w2="notebooks")

np.float32(-0.04237269)

In [9]:
model.wv.similarity(w1="notebooks",w2="notebooks")

np.float32(0.99999994)

In [10]:
print(len(vocab))

48
