#NUMPY

In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,4,5])

In [3]:
myarr

array([1, 2, 3, 4, 5])

In [4]:
myarr = np.array([[1,2,3,4]],np.int64)

In [5]:
myarr[0,1]

np.int64(2)

In [6]:
myarr = np.array([1,2,3,4],np.int64)

In [7]:
myarr[0]

np.int64(1)

In [8]:
myarr.shape

(4,)

In [9]:
myarr = np.array([[1,2,3,4]],np.int64)

In [10]:
myarr.shape

(1, 4)

In [11]:
myarr.dtype

dtype('int64')

In [12]:
myarr[0,1]=45

In [13]:
myarr

array([[ 1, 45,  3,  4]])

In [14]:
#Array creation : conversion from python structures 

In [15]:
listarry = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [16]:
listarry

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarry.dtype

dtype('int64')

In [18]:
listarry.shape

(3, 3)

In [19]:
listarry.size

9

In [20]:
zeros = np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng = np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,11,5)

In [25]:
lspace

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [26]:
emp = np.empty((4,6))

In [27]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [1.29060871e-306, 6.23055651e-307, 1.06811422e-306,
        3.56043054e-307, 1.37961641e-306, 1.05695167e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306, 8.01097889e-307],
       [1.78021527e-306, 9.34598926e-307, 1.11261434e-306,
        6.89811941e-307, 1.24611741e-306, 2.56765117e-312]])

In [28]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [30]:
ide = np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [32]:
ide.shape

(45, 45)

In [33]:
arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr = arr.reshape(3,33)

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr = arr.ravel()

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar.sum(axis=0)

array([12,  8,  9])

In [44]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [46]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

72

In [53]:
one = np.array([1,3,4,634,3])

In [54]:
one.argmax()

np.int64(3)

In [55]:
one.argmin()

np.int64(0)

In [56]:
one.argsort()

array([0, 1, 4, 2, 3])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.argmin()

np.int64(8)

In [59]:
ar.argmax()

np.int64(6)

In [60]:
ar.argmax(axis=0)

array([2, 1, 1])

In [61]:
ar.argmax(axis=1)

array([2, 2, 0])

In [62]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [63]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [64]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [65]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [72]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [74]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [75]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [76]:
ar.sum()

np.int64(29)

In [77]:
ar.max()

np.int64(7)

In [78]:
ar.min()

np.int64(0)

In [80]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [81]:
type(np.where(ar>5))

tuple

In [82]:
np.count_nonzero(ar)

np.int64(8)

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))